### PR TITLE
add ssl field to node driver settings

### PR DESCRIPTION
**Pull request by sh-dave**
To connect to a database in azure, SSL options might be required. Using an empty `ssl: {}` already did the trick for me and typing the whole node tls-options mentioned [here](https://github.com/mysqljs/mysql#ssl-options) felt like overkill for now so i went with `Any`.

### CODE REVIEW

**Comment by kevinresol** [comment]
I guess you can just use https://github.com/HaxeFoundation/hxnodejs/blob/506d4ed3be1ba47e2fd1b5b83f010745d585392f/src/js/node/tls/SecureContext.hx#L27

**Comment by kevinresol** [comment]
Is `haxe.extern.EitherType` not working for you or for any reason this custom abstract is needed?

**Comment by sh-dave** [comment]
Yes, i didn't know about it until now :sweat_smile:

**Comment by kevinresol** [comment]
Thanks!

**Pull request merged**
