### PR TITLE
Data types

### PR DESCRIPTION
**Pull request by kevinresol**
@benmerckx I am afraid I am messing up the formatter, could you have a quick look?

### CODE REVIEW

**Comment by benmerckx** [comment]
Don't see an issue at first glance? Not sure if mysql actually reports the integer types back the same way, but I can set up a test for that afterwards if you like.

**Comment by kevinresol** [comment]
Okay, btw what do we want to do with the `Float(m, d)` type?

**Comment by benmerckx** [comment]
Haxe docs describe a Float as [`double-precision IEEE 64bit float`](https://api.haxe.org/Float.html). That should probably match mysqls [`DOUBLE`](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html) type. I think it's probably best to find the best possible representation of a haxe Float in the backing database, because the decimal precision notation is I think mysql specific.

**Comment by kevinresol** [comment]
Let's merge and go on

**Pull request merged**
