### PR TITLE
[WIP] Scalar subqueries

### PR DESCRIPTION
**Pull request by benmerckx**
This allows comparing fields with scalar subqueries and adds any/some/exists functions. Needs cleanup and proper tests. It includes #70 too because I'm bad at git, will try to fix that :)
Comparison with constant expressions is not supported and maybe doesn't have to be.

### CODE REVIEW

**Comment by kevinresol** [comment]
What is blocking here? Anything I can help?

**Comment by benmerckx** [comment]
It's been a while :) I think by cleanup I meant I wanted to unify the way we get the field/filter types in macro world so that it could be used here, in joins and to introduce it in orderBy and groupBy. That can definitely be seen as a separate effort though. Other than that I also realized in some situations subqueries have access to the parent query fields which I believe is not supported here. But if you feel like fixing conflicts and merging, the current implementation is a pretty good start.

**Comment by kevinresol** [comment]
Rebased to master and tests are green. Perhaps we should merge first so we don't need to deal with a massive change set?

**Comment by benmerckx** [comment]
Sounds good :)

**Pull request merged**
