### PR TITLE
Query

### LINKED ISSUE #40: Check for null in the `==` expression
```haxe
var ident = getNull();
db.table.where(table.field == ident)
```

I think this is going to generate some strange SQL. The formatter should check for a null at runtime and generate `IS NULL` instead.

### LINKED ISSUE #57: Failed test
Was trying to implement #38 while I found a strange problem, if I change the value to `6` at [this line](https://github.com/haxetink/tink_sql/blob/5240624/src/tink/sql/drivers/node/MySql.hx#L31) then the diffEmpty test fails, any idea? @benmerckx

### PR DESCRIPTION
**Pull request by benmerckx**
Here's my second try at a PR :) This unfortunately changes a lot, but I like to think I got more done than I would have trying to do this incrementally. Feel free to close if this is not the way to do it. Here's an overview of the changes:
- Add tink.sql.Query (from #58), decided to call it Query instead of Sql without any good reason :)
- Updated node/php drivers to accept a `Query`. They needed to expose their formatter too for the schema diffing. This changes `Connection` to:
````haxe
interface Connection<Db> {
  function getFormatter():Formatter;
  function execute<Result>(query:Query<Db, Result>):Result;
}
````
- Replaced Format with SqlFormatter/MySqlFormatter. I tried to move MySql specific formatting to the subclass, but we'll probably need to move more things around once we revive the StdDriver (and test Sqlite).
- I rewrote the schema diffing with what I've learned since. The formatter now takes care of database specific info, which feels like a better place to put it. Alter table queries are bundled for MySql which makes the schema updates much faster and I've not experienced any more "random" failures (#57).
- TableInfo got a `getKeys` method, as I separated index info from column info (fixes #57 and #47 partially, adding the extra metadata won't take long). I've renamed the other methods to avoid confusion between "fields" and "columns" (`Field`/`Column`).
- Added `union`: `db.Table.where(...).union(db.Table.where(...))`
- Fixed #40 while down there
- Added support for default values `@:byDefault(true) var bool(default, null):Boolean`

I tried to not touch the user facing API at first, but some changes were needed:
- Moved `orderBy` and `limit` to methods in Dataset. This is needed to properly encapsulate queries fully. Say you want to create a union between two queries which are ordered or limited differently (or use a different order/limit for subqueries than their query they're used in).
- Added `groupBy`. I think `orderBy` and `groupBy` can be revised a bit more as they won't work as expected when doing a join (you'll have to get the tables from fields yourself instead of receiving multiple function arguments).

Some things I found out along the way:
- We were creating FLOAT types as FLOAT(X), but MySql actually expects them with two values as in [FLOAT(M,D)](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html). The FLOAT(X) format defaults to FLOAT. I've changed to the code to reflect this, but we might need to decide to either drop the "bits" or add a second value there to configure the precision.
- SqlLite does not support removing or modifying columns (unless you create a new table and copy the old records). I've changed `diffSchema()` to `diffSchema(destructive = false)` so we can eventually partially support schema changes, and it also felt like a more sane default (not removing columns, only adding).
- There were no tests for delete. I've added one simple test in `Run`, but we should probably expand on that.

I was trying to work in subqueries too. They're now easy to represent with `Query` and easy to format, but I need some help with representing those properly in the type system, I'll open a separate issue for discussion.

### CODE REVIEW

**Comment by kevinresol** [comment]
OMG this is awesome!

**Comment by back2dos** [comment]
What Kevin said! :)

I'll need a moment to process this ^^

**Comment by back2dos** [comment]
Ok, I still haven't gone through everything in detail. But the API looks neat and the tests are just fine, so let's merge this piece of awesomeness :)

**Comment by benmerckx** [comment]
Floats were adjusted in https://github.com/haxetink/tink_sql/pull/68, so we're not relying on deprecated syntax anymore

**Pull request merged**
