### PR TITLE
Revive std driver & start sqlite

### PR DESCRIPTION
**Pull request by benmerckx**
This is a draft that does:
- Prefixing all fields if we're joining tables. Settled on '$table@@@$field'. Clever minds can probably tell me how this would fail and what a better format might look like?
- Typing expressions. This is needed because haxe sys.db.ResultSet gives us no way to get the type. We need a lot of type conversion to present a consistent result across targets/drivers so this seems like the only way to get there. It does simplify implementing drivers a lot. (See `tink.sql.expr.ExprType`).
- Moves `Functions` and `Field` to `tink.sql.expr` since `Expr` was ready to explode, left typedefs in`tink.sql.Expr` for backwards compatibility.
- Slight change to `Sanitizer` value (non string values are properly encoded).

Led me to try implementing sqlite on nodejs side too. I tried `better-sqlite3` but it doesn't supply any sanitizing methods except for prepared statements. Which makes me think about implementing our formatters to return something like this instead of a String:
````haxe
private enum Part {
  Sql(query:String);
  Ident(name:String);
  Value(value:Any);
}

abstract Statement(Array<Part>) {...}
````
So we might sanitize it afterwards or use the drivers prepared statements to do so?

### CODE REVIEW

**Comment by kevinresol** [comment]
Just a quick note: the table-field encoding could be useful for #25 as well

**Comment by back2dos** [comment]
LGTM. Feel free to merge ;)

**Comment by benmerckx** [comment]
Let me plug this into an existing codebase first and see what happens :)

**Comment by benmerckx** [comment]
Coming back to this I think this needs to:

- [ ] Type fields once per query, not per row
- [ ] For php we need to keep a separate driver, having both the std driver and this do a conversion weighs on performance

**Pull request merged**
