### PR TITLE
Create table

### PR DESCRIPTION
**Pull request by kevinresol**
WIP.

### CODE REVIEW

**Comment by kevinresol** [comment]
Sort of done for now...

- Added @:autoIncrement / @:primary / @:unique
- Removed the spod's create table statements in flavour of the new tink_sql functions
- Create/drop tables in @:before @:after blocks in the tests

I think there are quite a lot of create table options there. Needa sort out what to include.

**Comment by kevinresol** [comment]
A few things to follow up from here:

- kind of duplicate functions: table.getFields() vs table.fieldnames()
- need a way to specify column size, maybe @:size(x)

**Comment by back2dos** [comment]
This is awesome :)

> need a way to specify column size, maybe @:size(x)

How about using types for that, e.g. `Text<140>`, `Blob<65000>`? It's kind of what the `tink.sql.types` package was intended for ^^

**Comment by kevinresol** [comment]
right, reminds me of the spod way
shall we merge this first and address that later?

**Pull request merged**
